- name: yum install bacepackage
  yum: name={{ item }} state=present
  with_items:
    - vim
    - zsh
    - git
    - tree
    - htop
    - iftop
    - mlocate
    - telnet
    - wget
    - ipa-pgothic-fonts

- name: stop firewalld
  service: name=firewalld state=stopped
